### ISSUE TITLE
When i try to run.bat

### ISSUE THREAD

**Issue by Mxngoe** [shinixsensei-dev/discord64#2]
log4j:WARN No appenders could be found for logger (com.sedmelluq.discord.lavaplayer.tools.io.TrustManagerBuilder).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
javax.security.auth.login.LoginException: Provided token was null or empty!
        at net.dv8tion.jda.core.entities.impl.JDAImpl.login(JDAImpl.java:195)
        at net.dv8tion.jda.core.JDABuilder.build(JDABuilder.java:913)
        at net.dv8tion.jda.core.JDABuilder.buildBlocking(JDABuilder.java:824)
        at net.dv8tion.jda.core.JDABuilder.buildBlocking(JDABuilder.java:852)
        at Core.Main.main(Main.java:37)

**Comment by crnvl** [comment]
It seems like your token is invalid. Remember, you need to use a client token, not a Bot Token. Bot Token won't work.

**Comment by crnvl** [comment]
You need to fill out the "token" value in the config.properties

**Comment by Mxngoe** [comment]
@shinixsensei-dev yeah I've put my token in the config and saved it but when I try to run it it just does that

**Comment by crnvl** [comment]
You need to close the program to edit the config. otherwise it won't be saved

**Comment by Mxngoe** [comment]
Yes I know I need to close the program to save it but every time I try to run the .bat it just says that no matter what I change in the config

**Comment by crnvl** [comment]
Maybe your client token changed. Try to get your token again

**Comment by Mxngoe** [comment]
You're right my token did change but now when I try to run the .bat it says 

log4j:WARN No appenders could be found for logger (com.sedmelluq.discord.lavaplayer.tools.io.TrustManagerBuilder).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Comment by crnvl** [comment]
Thats not a problem, just leave it as it is. The Program should start properly from now on.
