### ISSUE TITLE
I managed to connect the bot with my user but nothing works

### ISSUE THREAD

**Issue by sheeto** [shinixsensei-dev/discord64#4]
So I am now able to see:
Connected with Discord user [Name]
Detected with Email: [Name]
Discord tag: [Name]

but how do I continue now?

**Comment by sheeto** [comment]
And how does the autospammer work?

**Comment by crnvl** [comment]
There are some commands
Trigger them with [your prefix]spammer
for example

**Comment by crnvl** [comment]
I added a command list to the readme file

**Comment by Cheese-strat** [comment]
How did you get it to fix the
Unable to access jarfile discord64.jar
Error?

**Comment by crnvl** [comment]
Is the .bat file in the same folder with the .jar file?
