### ISSUE TITLE
error.

### ISSUE THREAD

**Issue by sheeto** [shinixsensei-dev/discord64#6]
it's giving me this error now.

log4j:WARN No appenders could be found for logger (com.sedmelluq.discord.lavaplayer.tools.io.TrustManagerBuilder).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Comment by crnvl** [comment]
Thats just a normal warning. Everything should work tho. Just ignore those warnings
